blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/kanyingidickson-dev/Open-Issue-Finder/discussions
    about: Please ask and answer questions here.
